### ISSUE TITLE
Identity block

### ISSUE THREAD

**Issue by dkoguciuk** [ruizengalways/PFNet#3]
Hi @ruizengalways ,

I've got a question about the identity block. In the [paper](https://eprints.qut.edu.au/126933/1/0654.pdf), on figure 2 the identity block has additional **1x1conv** and **batch norm** on the shortcut connection:

![Screenshot from 2020-08-18 11-47-29](https://user-images.githubusercontent.com/9368849/90498517-ba6fb780-e148-11ea-81cd-46b1f560df4a.png)

But in the code, there is no 1x1conv + bn in the identity block:

```
    x = KL.Add()([x, input_tensor])
    x = KL.Activation('relu', name='res' + str(branch) + str(stage) + block + '_out')(x)
```

So, what's the proper design here?

Best,
Daniel

**Comment by ruizengalways** [comment]
Hi Daniel,

Thanks for pointing out this. The residual blocks are directly adopted from https://github.com/matterport/Mask_RCNN. I did not use conv 1x1 here. Basically, the encoder part of this network is the standard ResNet. This was a mistake. I will corect it in this repo.

Best regards,
Rui

**Comment by dkoguciuk** [comment]
Hi Rui,

sure, thanks!

Best,
Daniel
